### ISSUE TITLE
imgur is No longer talking to telegram bot

### ISSUE THREAD

**Issue by juanpc2018** [therealaleph/OSINT#1]
try other...
https://yandex.com/search/?text=image+hosting

needs a .ru compatible image hosting.
https://browser.yandex.com  Ai allows to translate text in images, document.
but some websites, Not all

https://twitter.com/no_itsmyturn/status/1500044807783264257

Telegram Translator Bot, does Not translate images, only Browser and Web...
https://trasnlate.yandex.com

**Comment by therealaleph** [comment]
Works fine by my side. Check your credentials?

**Comment by juanpc2018** [comment]
working again...
probably needed a re /start again
